spring.application.name=TP 13 Integration OAuth2 Google ou Keycloak
server.port=8081

spring.security.oauth2.client.registration.google.client-id=
spring.security.oauth2.client.registration.google.client-secret=
spring.security.oauth2.client.registration.google.scope=openid,profile,email

spring.security.oauth2.client.provider.google.issuer-uri=https://accounts.google.com